name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      pages: write    
      id-token: write  
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.7

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.4


